**Additional exercises**

1. Project Euler, Problem 18: https://projecteuler.net/problem=18
- No need to create graph: the source node is the top, unvisited neighbors are always the two numbers directly below. A dynamical programming solution can also be given, but may be more costly.

  

In [1]:
import numpy as np

A = [[3,0,0,0],
     [7,4,0,0],
     [2,4,6,0],
     [8,5,9,3]]

A = np.array(A)

print(A)

[[3 0 0 0]
 [7 4 0 0]
 [2 4 6 0]
 [8 5 9 3]]


Remarks:
- nodes below value on position $i$ have indices $i$ and $i+1$
- we will keep a matrix having the same size as `A` and we'll update the value of a node if a **bigger** value is found
- 

In [2]:
nrows = A.shape[0]  # number of rows in A

Cost = np.zeros(A.shape)

Cost[0][0] = A[0][0]

print(A)

for i in range(1,nrows):
    for j in range(0,i):
        #print(i," ",j," ",A[i][j])
        vleft = Cost[i-1][j]+A[i][j]
        vright = Cost[i-1][j]+A[i][j+1]
        if vleft>Cost[i,j]:
            Cost[i,j] = vleft
        if vright>Cost[i,j+1]:
            Cost[i,j+1] = vright
    print(Cost)

[[3 0 0 0]
 [7 4 0 0]
 [2 4 6 0]
 [8 5 9 3]]
[[ 3.  0.  0.  0.]
 [10.  7.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 3.  0.  0.  0.]
 [10.  7.  0.  0.]
 [12. 14. 13.  0.]
 [ 0.  0.  0.  0.]]
[[ 3.  0.  0.  0.]
 [10.  7.  0.  0.]
 [12. 14. 13.  0.]
 [20. 19. 23. 16.]]


In [4]:
def maxPyramid(A):
    nrows = A.shape[0]  # number of rows in A

    Cost = np.zeros(A.shape)

    Cost[0][0] = A[0][0]

    print(A)

    prev = np.zeros(A.shape)
    print(prev)

    for i in range(1,nrows):
        for j in range(0,i):
            #print(i," ",j," ",A[i][j])
            vleft = Cost[i-1][j]+A[i][j]
            vright = Cost[i-1][j]+A[i][j+1]
            if vleft>Cost[i,j]:
                Cost[i,j] = vleft
                prev[i,j] = j
            if vright>Cost[i,j+1]:
                Cost[i,j+1] = vright
                prev[i,j+1] = j
    return max(Cost[-1]), prev, Cost[-1]

maxPyramid(A)

[[3 0 0 0]
 [7 4 0 0]
 [2 4 6 0]
 [8 5 9 3]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(np.float64(23.0),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 1., 2.]]),
 array([20., 19., 23., 16.]))

In [5]:
def readTriMat(s):
    L = []
    with open(s) as file:
        for line in file:
            L.append(np.fromstring(line,sep=" "))
    #print(L)

    BigA = np.zeros((len(L),len(L)))
    for i in range(0,len(L)):
        #print(L[i])
        #print(BigA[i][0:i+1])
        BigA[i][0:i+1] = L[i]
    return (BigA)
    
BigA = readTriMat('0067_triangle.txt')

maxPyramid(BigA)

[[59.  0.  0. ...  0.  0.  0.]
 [73. 41.  0. ...  0.  0.  0.]
 [52. 40.  9. ...  0.  0.  0.]
 ...
 [64. 66. 84. ... 15.  0.  0.]
 [30. 11. 85. ... 67. 68.  0.]
 [23. 33. 44. ... 59. 63. 35.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


(np.float64(7273.0),
 array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  1.,  1., ..., 96.,  0.,  0.],
        [ 0.,  1.,  2., ..., 96., 97.,  0.],
        [ 0.,  1.,  2., ..., 96., 97., 98.]], shape=(100, 100)),
 array([5139., 5362., 5465., 5509., 5591., 5779., 5783., 5821., 5840.,
        5874., 5872., 6176., 6170., 6337., 6283., 6395., 6420., 6519.,
        6522., 6580., 6721., 6737., 6705., 6724., 6720., 6725., 6745.,
        6793., 6886., 6884., 6806., 6918., 6888., 6866., 6933., 7007.,
        7007., 7030., 7042., 7012., 7011., 6967., 6950., 7099., 7099.,
        7129., 7099., 7049., 7021., 7202., 7179., 7197., 7225., 7273.,
        7181., 7141., 7178., 7229., 7200., 7184., 7192., 7195., 7251.,
        7195., 7191., 7245., 7182., 7244., 7198., 7179., 7168., 6969.,
        7002., 6950., 6973., 6917., 6827., 6810., 6868., 6704., 6633.,
        6699., 6622., 6508., 6548., 6

2. Project Euler, problem 81: https://projecteuler.net/problem=81   
- there is no need to create a graph, just apply Dijkstra's algorithm on the matrix, observing the unvisited neighbors of a current element

In [65]:
A = np.array([[131 ,673, 234, 103, 18],
             [201,96,342,965,150],
             [630,803,746,422,111],
             [537,699,497,121,956],
             [805,732,524,37,331]])

print(A)

[[131 673 234 103  18]
 [201  96 342 965 150]
 [630 803 746 422 111]
 [537 699 497 121 956]
 [805 732 524  37 331]]


To explore the matrix we go either right or down. Start from the top left node and visit all elements. Replace value in cost matrix if it is smaller than before.



In [71]:
# initialize with infinity since we are looking for shortest paths

Cost = np.matrix(np.ones(A.shape) * np.inf)
print(Cost)

queue = [(0,0)]
nmax = len(Cost)

Cost[0,0] = A[0,0]

while len(queue)>0:
    # pop the first element
    q = queue.pop(0);
    i = q[0]
    j = q[1]
    
    # down 
    if (i+1)<nmax:
        nextl = (i+1,j)
        queue.append(nextl)
        nextcost = Cost[i,j]+A[i+1,j]
        if nextcost<Cost[i+1,j]:
            Cost[i+1,j] = nextcost
    # left
    if (j+1)<nmax:
        nextl = (i,j+1)
        queue.append(nextl)
        nextcost = Cost[i,j]+A[i,j+1]
        if nextcost<Cost[i,j+1]:
            Cost[i,j+1] = nextcost

print(Cost)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]
[[ 131.  804. 1038. 1141. 1159.]
 [ 332.  428.  770. 1735. 1309.]
 [ 962. 1231. 1516. 1938. 1420.]
 [1499. 1930. 2013. 2059. 2376.]
 [2304. 2662. 2537. 2096. 2427.]]


3. Project Euler, problem 82: https://projecteuler.net/problem=82
- note that the minimal distance from any element on the left column to any element of the right column needs to be computed. It is possible to run Dijkstra's algorithm for all starting nodes on the left and record the minimal path length.
- Problem 83 from Project Euler adds another complication